Lvl_Tuto_map = [
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXOX                                         XOXX',
    'XXXOX                                         XOXX',
    'XXXOX                                         XOXX',
    'XXXOX                                         XOXX',
    'XXXOX                                    D    XOXX',
    'XXXOX        OXXXXX                    XXXX   XOXX',
    'XXXOX                                  O      XOXX',
    'XXXOX                                  O      XOXX',
    'XXXOX        X        X      XOOOXOOOXXO      XOXX',
    'XXXOX P  XOOO OOOOOOOO      O                 XOXX',
    'XXXXXXXOO                OXO                  XXXX',
]

Lvl_1_map = [
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXOX                                                                                                                                        XOXXXXXXXXXXX',
    'XXXOX                                                                                                                                        XOXXXXXXXXXXX',
    'XXXOX                OOXOOXOOXOOXOOXOOXX                                                                                                     XOXXXXXXXXXXX',
    'XXXOX            XXXO                  OOO   XOOXOOXX                    OXOOOX                                                              XOXXXXXXXXXXX',
    'XXXOX           OO                       OOXOOOOOOOOOOOOOX              O     OO                                                             XOXXXXXXXXXXX',
    'XXXOX  D   XOOOOOO     XXX                                OOOXOOOXOOOXO       OO                                                             XOXXXXXXXXXXX',
    'XXXOXXXOOOOO    OO       OOOOXXXX                         O                    O      O    O    O                            XXX             XOXXXXXXXXXXX',
    'XXXOX           OOXXXX           O       XXXXXXXXXXX      O                    OX     O    O    O                          OO                XOXXXXXXXXXXX',
    'XXXOX                             OXXXXOOO                O                     O     O    O    O     OXXOOXXXO          XX      XXXO        XOXXXXXXXXXXX',
    'XXXOX                              XO                     O                     OXXXXOOXXXOOXXXOOXXXXX        O        OO        O           XOXXXXXXXXXXX',
    'XXXOX             OXXXXXX  XX     XOO                 OXXXX                                                   OXXXO0XXX      XXXO            XOXXXXXXXXXXX',
    'XXXOX                            XOOO                OOXXXXXXXXXXXXX                                                         O               XOXXXXXXXXXXX',
    'XXXOX                           XOOOOOOO   XXXXXXXXXX    O    O    O      OOOOO    OOOO    OOOO    OOOO                  XXXO                XOXXXXXXXXXXX',
    'XXXOX      XXXXOOOXXXOOOOOXXXXXXXXXXO          OOO                        XXXXX    XXXX    XXXX    XXXX                  O                   XOXXXXXXXXXXX',
    'XXXOX      O                          O                                                                              XXXO                    XOXXXXXXXXXXX',
    'XXXOX P    O                           XXXXX          O    O    O    O                                               O                       XOXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXX                           OXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOOOOOOOXOOOOOOOXOOOOOOOXOOOOOOOXXXXXXXXXXX                        XXXXXXXXXXXXX',
    ]

Lvl_2_map = [
    "X                                                            XXXXXXXXXXX",
    "X                                                            XXXXXXXXXXX",
    "X                               D         X    X    X        XXXXXXXXXXX",
    "X                               XXXOOXX   O    O    O    X   XXXXXXXXXXX",
    "X                               O         O         O       XXXXXXXXXXXX",
    "X                               O                            XXXXXXXXXXX",
    "X                               O              O         X   XXXXXXXXXXX",
    "X        X    X    X            O         O    O    O X      XXXXXXXXXXX ",
    "X                               OX    XXXXXXXXXXXXXXOOOOO    XXXXXXXXXXX",
    "X      O      OOOOOOOOX          O                           XXXXXXXXXXX",
    "X      OX   OOO       O          O                           XXXXXXXXXXX",
    "X      X      O       O          O                           XXXXXXXXXXX",
    "X       X    OO       O          OXOO       OOOOOOOOOOOOOOOOOXXXXXXXXXXX",
    "X     OOO    XO       OOOOOXO       OOOXXX  O                XXXXXXXXXXX",
    "X       X     O       O     O               O                XXXXXXXXXXX",
    "X            XO       O     O               O                XXXXXXXXXXX",
    "X  P    XOOOOOO       O     OOOOOXOOXXXOOOOOO                XXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
]

Lvl_3_map = [
    "XXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXX ",
    "XXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXX ",
    "X                               OXXXXXXXXXXXXXXXXXXXXXXXXXX ",
    "X                   O           OOOOXXOXXXXXXXXXXXXXXXXXXXX",
    "X                X   X          O     OXXXXXXXXXXXXXXXXXXXX",
    "X              OOOO  O    X   XXX      XXXOOOXXXXXXXXXXXXXX",
    "X              O     OOOOO         XX      OXXXXXXXXXXXXXXX",
    "X              O      O             XXXX   OX             X",
    "X     X        XXXXX  O       XX    X      OX             X",
    "XX                    OOOOOOOOOOOOOOO   XXXX         O    X",
    "XO             XOOOOOOXXXXXXXXXXXXXXO            O   O    X",
    "XO        OXXOO            D        X         O  O   O    X",
    "XO    O     XXX       OOOOOXXXXX    XXXXXXXXXXXXXXXXXX    X",
    "XX X  O      XX       X                                   X",
    "XOOOOOO      XX        X                                  X",
    "XXXXXXX      XX         OX   O     O     O   O    O       X",
    "XXXXXXX   P  XX         XXX  O     O   XOOXXXXXXXXO       X",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
]
tile_size = 48
screen_width = 1500
screen_height = len(Lvl_1_map) * tile_size
obstacle_size = 32
